### PR TITLE
OK same sort of thing again

### PR DESCRIPTION
**Pull request by Link2Twenty**
I've imported polymer so you don't need to use window.Polymer and added it to the dependencies too.
Slightly simplyified the code
and added a little complexity to the demo

### CODE REVIEW

**Comment by rubenstolk** [comment]
OK manually pulled in a couple of changes, all good to go now!

**Comment by Link2Twenty** [comment]
as it stands your element only works if it's on a page that is importing polymer, it's much safer to import it in sc-timeago.html 
put this in before the moment.min.js

``` html
<link rel="import" href="../polymer/polymer.html" />
```

**Comment by Link2Twenty** [comment]
also in sc-timeago.html 

```
this.set('timeago', window.moment(datetime).fromNow());
```

needs to be 

```
this.set('timeago', window.moment(this.datetime).fromNow());
```

in order to work.

**Comment by rubenstolk** [comment]
Right thanks! Fixed that. From now on, feel free to send in PR's again, keep them tiny and small so it's easier to merge them :)

**Pull request closed without merging**
